version: "3"

services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cij-db
    ports:
      - 5432:5432
    networks:
      - shared-network
    volumes:
      - ./postgres-db:/var/lib/postgresql/data

  api:
    container_name: cij_api
    image: node:18-alpine
    build:
      context: api
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
      - shared-network
    volumes:
      - ./api/src:/api/src
    depends_on:
      - postgres

  client:
    container_name: cij_client
    image: docker-nextjs-dev
    build:
      context: client
      target: dev
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
